#!/bin/bash
set -e

update_data() {
  cd ~/src/github/Metastring/healthheatmap-data
  git pull
  systemctl --user start hhm-data
}

update_api() {
  cd ~/src/github/Metastring/health-heat-map-api
  git pull
  ./mvnw compile package
  systemctl --user restart hhm-api
}

for arg in "$@"; do
  if [ "$arg" == "--data" ] || [ "$arg" == "-d" ]; then
    echo "Requested to update data"
    update_data
  fi
  if [ "$arg" == "--api" ] || [ "$arg" == "-a" ]; then
    echo "Requested to update API"
    update_api
  fi
done
